const apidata = [
  {node: 'variable_color 引入scss变量时可用',
  s: true,
  countent: [
    {
      s: true,
      name: '$gray-0',
      type: 'color'
    },
    {
      s: true,
      name: '$gray-1',
      type: 'color'
    },
    {
      s: true,
      name: '$gray-2',
      type: 'color'
    },
    {
      s: true,
      name: '$gray-3',
      type: 'color'
    },
    {
      s: true,
      name: '$gray-4',
      type: 'color'
    },
    {
      s: true,
      name: '$gray-5',
      type: 'color'
    },
    {
      s: true,
      name: '$blue-0',
      type: 'color'
    },
    {
      s: true,
      name: '$blue-1',
      type: 'color'
    },
    {
      s: true,
      name: '$green-0',
      type: 'color'
    },
    {
      s: true,
      name: '$orange-0',
      type: 'color'
    },
    {
      s: true,
      name: '$red-0',
      type: 'color'
    }
  ]},
  {node: 'variable_size 引入scss变量时可用',
  s: true,
  countent: [
    {
      s: true,
      name: '$fz-s',
      type: 'size, 20px .833rem (20px)'
    },
    {
      s: true,
      name: '$fz',
      type: 'size, 24px 1rem (24px)'
    },
    {
      s: true,
      name: '$fz-m',
      type: 'size, 28px 1.16rem (28px)'
    },
    {
      s: true,
      name: '$fz-ml',
      type: 'size, 30px 1.25rem (30px)'
    },
    {
      s: true,
      name: '$fz-l',
      type: 'size, 32px 1.333rem (32px)'
    },
    {
      s: true,
      name: '$fz-ll',
      type: 'size, 36px 1.5rem (36px)'
    }
  ]},
  {node: 'variable_border_radius 引入scss变量时可用',
  s: true,
  countent: [
    {
      s: true,
      name: '$radius',
      type: 'radius, 10/24rem'
    }
  ]},
  {node: 'style_font_size 字体大小',
  s: true,
  countent: [
    {
      s: true,
      name: '.fz-s',
      type: 'font-size:.833rem (20px)'
    },
    {
      s: true,
      name: '.fz',
      type: 'font-size:1rem (24px)'
    },
    {
      s: true,
      name: '.fz-m',
      type: 'font-size:1.16rem (28px)'
    },
    {
      s: true,
      name: '.fz-ml',
      type: 'font-size:1.25rem (30px)'
    },
    {
      s: true,
      name: '.fz-l',
      type: 'font-size:1.333rem (32px)'
    },
    {
      s: true,
      name: '.fz-ll',
      type: 'font-size:1.5rem (36px)'
    },
    {
      s: true,
      name: '.fz-ll',
      type: 'font-size:1.5rem (36px)'
    }
  ]},
  {node: 'style_font_color 字体颜色',
  s: true,
  countent: [
    {
      s: true,
      name: '.gray-0',
      type: 'color'
    },
    {
      s: true,
      name: '.gray-1',
      type: 'color'
    },
    {
      s: true,
      name: '.gray-2',
      type: 'color'
    },
    {
      s: true,
      name: '.gray-3',
      type: 'color'
    },
    {
      s: true,
      name: '.gray-4',
      type: 'color'
    },
    {
      s: true,
      name: '.gray-5',
      type: 'color'
    },
    {
      s: true,
      name: '.white-0',
      type: 'color'
    },
    {
      s: true,
      name: '.blue-0',
      type: 'color'
    },
    {
      s: true,
      name: '.blue-1',
      type: 'color'
    },
    {
      s: true,
      name: '.green-0',
      type: 'color'
    },
    {
      s: true,
      name: '.orange-0',
      type: 'color'
    },
    {
      s: true,
      name: '.red-0',
      type: 'color'
    }
  ]},
  {node: 'style_background_color 背景色',
  s: true,
  countent: [
    {
      s: true,
      name: '.bg-gray-0',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-gray-1',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-gray-2',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-gray-3',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-gray-4',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-gray-5',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-white-0',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-blue-0',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-blue-1',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-green-0',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-orange-0',
      type: 'color'
    },
    {
      s: true,
      name: '.bg-red-0',
      type: 'color'
    }
  ]},
  {node: 'style_padding 内边距',
  s: true,
  countent: [
    {s: true,
      name: '.pd-1',
      type: 'padding:.1rem '},
    {s: true,
      name: '.pd-2',
      type: 'padding:.2rem '},
    {s: true,
      name: '.pd-3',
      type: 'padding:.3rem '},
    {s: true,
      name: '.pd-4',
      type: 'padding:.4rem '},
    {s: true,
      name: '.pd-5',
      type: 'padding:.5rem '},
    {s: true,
      name: '.pd-6',
      type: 'padding:.6rem '},
    {s: true,
      name: '.pd-7',
      type: 'padding:.7rem '},
    {s: true,
      name: '.pd-8',
      type: 'padding:.8rem '},
    {s: true,
      name: '.pd-9',
      type: 'padding:.9rem '},
    {s: true,
      name: '.pd1',
      type: 'padding:1rem '},
    {s: true,
      name: '.pd1-5',
      type: 'padding:1.5rem '},
    {s: true,
      name: '.pd2',
      type: 'padding:2rem '},
    {s: true,
      name: '.pd2-5',
      type: 'padding:2.5rem '},
    {s: true,
      name: '.pd3',
      type: 'padding:3rem '},
    {s: true,
      name: '.pd3-5',
      type: 'padding:3.5rem '},
    {s: true,
      name: '.pd4',
      type: 'padding:4rem '},
    {s: true,
      name: '.pd4-5',
      type: 'padding:4.5rem '},
    {s: true,
      name: '.pd5',
      type: 'padding:5rem '},
    {s: true,
      name: '.pd5-5',
      type: 'padding:5.5rem '},
    {s: true,
      name: '.pd6',
      type: 'padding:6rem '},
    {s: true,
      name: '.pd6-5',
      type: 'padding:6.5rem '},
    {s: true,
      name: '.pd7',
      type: 'padding:7rem '},
    {s: true,
      name: '.pd7-5',
      type: 'padding:7.5rem '},
    {s: true,
      name: '.pd8',
      type: 'padding:8rem '},
    {s: true,
      name: '.pd8-5',
      type: 'padding:8.5rem '},
    {s: true,
      name: '.pd9',
      type: 'padding:9rem '},
    {s: true,
      name: '.pd9-5',
      type: 'padding:9.5rem '},

    {s: true,
      name: '.pdb-1',
      type: 'padding-bottom:.1rem '},
    {s: true,
      name: '.pdb-2',
      type: 'padding-bottom:.2rem '},
    {s: true,
      name: '.pdb-3',
      type: 'padding-bottom:.3rem '},
    {s: true,
      name: '.pdb-4',
      type: 'padding-bottom:.4rem '},
    {s: true,
      name: '.pdb-5',
      type: 'padding-bottom:.5rem '},
    {s: true,
      name: '.pdb-6',
      type: 'padding-bottom:.6rem '},
    {s: true,
      name: '.pdb-7',
      type: 'padding-bottom:.7rem '},
    {s: true,
      name: '.pdb-8',
      type: 'padding-bottom:.8rem '},
    {s: true,
      name: '.pdb-9',
      type: 'padding-bottom:.9rem '},
    {s: true,
      name: '.pdb1',
      type: 'padding-bottom:1rem '},
    {s: true,
      name: '.pdb1-5',
      type: 'padding-bottom:1.5rem '},
    {s: true,
      name: '.pdb2',
      type: 'padding-bottom:2rem '},
    {s: true,
      name: '.pdb2-5',
      type: 'padding-bottom:2.5rem '},
    {s: true,
      name: '.pdb3',
      type: 'padding-bottom:3rem '},
    {s: true,
      name: '.pdb3-5',
      type: 'padding-bottom:3.5rem '},
    {s: true,
      name: '.pdb4',
      type: 'padding-bottom:4rem '},
    {s: true,
      name: '.pdb4-5',
      type: 'padding-bottom:4.5rem '},
    {s: true,
      name: '.pdb5',
      type: 'padding-bottom:5rem '},
    {s: true,
      name: '.pdb5-5',
      type: 'padding-bottom:5.5rem '},
    {s: true,
      name: '.pdb6',
      type: 'padding-bottom:6rem '},
    {s: true,
      name: '.pdb6-5',
      type: 'padding-bottom:6.5rem '},
    {s: true,
      name: '.pdb7',
      type: 'padding-bottom:7rem '},
    {s: true,
      name: '.pdb7-5',
      type: 'padding-bottom:7.5rem '},
    {s: true,
      name: '.pdb8',
      type: 'padding-bottom:8rem '},
    {s: true,
      name: '.pdb8-5',
      type: 'padding-bottom:8.5rem '},
    {s: true,
      name: '.pdb9',
      type: 'padding-bottom:9rem '},
    {s: true,
      name: '.pdb9-5',
      type: 'padding-bottom:9.5rem '},

    {s: true,
      name: '.pdt-1',
      type: 'padding-top:.1rem '},
    {s: true,
      name: '.pdt-2',
      type: 'padding-top:.2rem '},
    {s: true,
      name: '.pdt-3',
      type: 'padding-top:.3rem '},
    {s: true,
      name: '.pdt-4',
      type: 'padding-top:.4rem '},
    {s: true,
      name: '.pdt-5',
      type: 'padding-top:.5rem '},
    {s: true,
      name: '.pdt-6',
      type: 'padding-top:.6rem '},
    {s: true,
      name: '.pdt-7',
      type: 'padding-top:.7rem '},
    {s: true,
      name: '.pdt-8',
      type: 'padding-top:.8rem '},
    {s: true,
      name: '.pdt-9',
      type: 'padding-top:.9rem '},
    {s: true,
      name: '.pdt1',
      type: 'padding-top:1rem '},
    {s: true,
      name: '.pdt1-5',
      type: 'padding-top:1.5rem '},
    {s: true,
      name: '.pdt2',
      type: 'padding-top:2rem '},
    {s: true,
      name: '.pdt2-5',
      type: 'padding-top:2.5rem '},
    {s: true,
      name: '.pdt3',
      type: 'padding-top:3rem '},
    {s: true,
      name: '.pdt3-5',
      type: 'padding-top:3.5rem '},
    {s: true,
      name: '.pdt4',
      type: 'padding-top:4rem '},
    {s: true,
      name: '.pdt4-5',
      type: 'padding-top:4.5rem '},
    {s: true,
      name: '.pdt5',
      type: 'padding-top:5rem '},
    {s: true,
      name: '.pdt5-5',
      type: 'padding-top:5.5rem '},
    {s: true,
      name: '.pdt6',
      type: 'padding-top:6rem '},
    {s: true,
      name: '.pdt6-5',
      type: 'padding-top:6.5rem '},
    {s: true,
      name: '.pdt7',
      type: 'padding-top:7rem '},
    {s: true,
      name: '.pdt7-5',
      type: 'padding-top:7.5rem '},
    {s: true,
      name: '.pdt8',
      type: 'padding-top:8rem '},
    {s: true,
      name: '.pdt8-5',
      type: 'padding-top:8.5rem '},
    {s: true,
      name: '.pdt9',
      type: 'padding-top:9rem '},
    {s: true,
      name: '.pdt9-5',
      type: 'padding-top:9.5rem '},

    {s: true,
      name: '.pdl-1',
      type: 'padding-left:.1rem '},
    {s: true,
      name: '.pdl-2',
      type: 'padding-left:.2rem '},
    {s: true,
      name: '.pdl-3',
      type: 'padding-left:.3rem '},
    {s: true,
      name: '.pdl-4',
      type: 'padding-left:.4rem '},
    {s: true,
      name: '.pdl-5',
      type: 'padding-left:.5rem '},
    {s: true,
      name: '.pdl-6',
      type: 'padding-left:.6rem '},
    {s: true,
      name: '.pdl-7',
      type: 'padding-left:.7rem '},
    {s: true,
      name: '.pdl-8',
      type: 'padding-left:.8rem '},
    {s: true,
      name: '.pdl-9',
      type: 'padding-left:.9rem '},
    {s: true,
      name: '.pdl1',
      type: 'padding-left:1rem '},
    {s: true,
      name: '.pdl1-5',
      type: 'padding-left:1.5rem '},
    {s: true,
      name: '.pdl2',
      type: 'padding-left:2rem '},
    {s: true,
      name: '.pdl2-5',
      type: 'padding-left:2.5rem '},
    {s: true,
      name: '.pdl3',
      type: 'padding-left:3rem '},
    {s: true,
      name: '.pdl3-5',
      type: 'padding-left:3.5rem '},
    {s: true,
      name: '.pdl4',
      type: 'padding-left:4rem '},
    {s: true,
      name: '.pdl4-5',
      type: 'padding-left:4.5rem '},
    {s: true,
      name: '.pdl5',
      type: 'padding-left:5rem '},
    {s: true,
      name: '.pdl5-5',
      type: 'padding-left:5.5rem '},
    {s: true,
      name: '.pdl6',
      type: 'padding-left:6rem '},
    {s: true,
      name: '.pdl6-5',
      type: 'padding-left:6.5rem '},
    {s: true,
      name: '.pdl7',
      type: 'padding-left:7rem '},
    {s: true,
      name: '.pdl7-5',
      type: 'padding-left:7.5rem '},
    {s: true,
      name: '.pdl8',
      type: 'padding-left:8rem '},
    {s: true,
      name: '.pdl8-5',
      type: 'padding-left:8.5rem '},
    {s: true,
      name: '.pdl9',
      type: 'padding-left:9rem '},
    {s: true,
      name: '.pdl9-5',
      type: 'padding-left:9.5rem '},

    {s: true,
      name: '.pdr-1',
      type: 'padding-right:.1rem '},
    {s: true,
      name: '.pdr-2',
      type: 'padding-right:.2rem '},
    {s: true,
      name: '.pdr-3',
      type: 'padding-right:.3rem '},
    {s: true,
      name: '.pdr-4',
      type: 'padding-right:.4rem '},
    {s: true,
      name: '.pdr-5',
      type: 'padding-right:.5rem '},
    {s: true,
      name: '.pdr-6',
      type: 'padding-right:.6rem '},
    {s: true,
      name: '.pdr-7',
      type: 'padding-right:.7rem '},
    {s: true,
      name: '.pdr-8',
      type: 'padding-right:.8rem '},
    {s: true,
      name: '.pdr-9',
      type: 'padding-right:.9rem '},
    {s: true,
      name: '.pdr1',
      type: 'padding-right:1rem '},
    {s: true,
      name: '.pdr1-5',
      type: 'padding-right:1.5rem '},
    {s: true,
      name: '.pdr2',
      type: 'padding-right:2rem '},
    {s: true,
      name: '.pdr2-5',
      type: 'padding-right:2.5rem '},
    {s: true,
      name: '.pdr3',
      type: 'padding-right:3rem '},
    {s: true,
      name: '.pdr3-5',
      type: 'padding-right:3.5rem '},
    {s: true,
      name: '.pdr4',
      type: 'padding-right:4rem '},
    {s: true,
      name: '.pdr4-5',
      type: 'padding-right:4.5rem '},
    {s: true,
      name: '.pdr5',
      type: 'padding-right:5rem '},
    {s: true,
      name: '.pdr5-5',
      type: 'padding-right:5.5rem '},
    {s: true,
      name: '.pdr6',
      type: 'padding-right:6rem '},
    {s: true,
      name: '.pdr6-5',
      type: 'padding-right:6.5rem '},
    {s: true,
      name: '.pdr7',
      type: 'padding-right:7rem '},
    {s: true,
      name: '.pdr7-5',
      type: 'padding-right:7.5rem '},
    {s: true,
      name: '.pdr8',
      type: 'padding-right:8rem '},
    {s: true,
      name: '.pdr8-5',
      type: 'padding-right:8.5rem '},
    {s: true,
      name: '.pdr9',
      type: 'padding-right:9rem '},
    {s: true,
      name: '.pdr9-5',
      type: 'padding-right:9.5rem '}
  ]},
  {node: 'style_margin 外边距',
  s: true,
  countent: [
    {s: true,
      name: '.mg-1',
      type: 'margin:.1rem' },
    {s: true,
      name: '.mg-2',
      type: 'margin:.2rem' },
    {s: true,
      name: '.mg-3',
      type: 'margin:.3rem' },
    {s: true,
      name: '.mg-4',
      type: 'margin:.4rem' },
    {s: true,
      name: '.mg-5',
      type: 'margin:.5rem' },
    {s: true,
      name: '.mg-6',
      type: 'margin:.6rem' },
    {s: true,
      name: '.mg-7',
      type: 'margin:.7rem' },
    {s: true,
      name: '.mg-8',
      type: 'margin:.8rem' },
    {s: true,
      name: '.mg-9',
      type: 'margin:.9rem' },
    {s: true,
      name: '.mg1',
      type: 'margin:1rem' },
    {s: true,
      name: '.mg1-5',
      type: 'margin:1.5rem' },
    {s: true,
      name: '.mg2',
      type: 'margin:2rem' },
    {s: true,
      name: '.mg2-5',
      type: 'margin:2.5rem' },
    {s: true,
      name: '.mg3',
      type: 'margin:3rem' },
    {s: true,
      name: '.mg3-5',
      type: 'margin:3.5rem' },
    {s: true,
      name: '.mg4',
      type: 'margin:4rem' },
    {s: true,
      name: '.mg4-5',
      type: 'margin:4.5rem' },
    {s: true,
      name: '.mg5',
      type: 'margin:5rem' },
    {s: true,
      name: '.mg5-5',
      type: 'margin:5.5rem' },
    {s: true,
      name: '.mg6',
      type: 'margin:6rem' },
    {s: true,
      name: '.mg6-5',
      type: 'margin:6.5rem' },
    {s: true,
      name: '.mg7',
      type: 'margin:7rem' },
    {s: true,
      name: '.mg7-5',
      type: 'margin:7.5rem' },
    {s: true,
      name: '.mg8',
      type: 'margin:8rem' },
    {s: true,
      name: '.mg8-5',
      type: 'margin:8.5rem' },
    {s: true,
      name: '.mg9',
      type: 'margin:9rem' },
    {s: true,
      name: '.mg9-5',
      type: 'margin:9.5rem' },

    {s: true,
      name: '.mgb-1',
      type: 'margin-bottom:.1rem' },
    {s: true,
      name: '.mgb-2',
      type: 'margin-bottom:.2rem' },
    {s: true,
      name: '.mgb-3',
      type: 'margin-bottom:.3rem' },
    {s: true,
      name: '.mgb-4',
      type: 'margin-bottom:.4rem' },
    {s: true,
      name: '.mgb-5',
      type: 'margin-bottom:.5rem' },
    {s: true,
      name: '.mgb-6',
      type: 'margin-bottom:.6rem' },
    {s: true,
      name: '.mgb-7',
      type: 'margin-bottom:.7rem' },
    {s: true,
      name: '.mgb-8',
      type: 'margin-bottom:.8rem' },
    {s: true,
      name: '.mgb-9',
      type: 'margin-bottom:.9rem' },
    {s: true,
      name: '.mgb1',
      type: 'margin-bottom:1rem' },
    {s: true,
      name: '.mgb1-5',
      type: 'margin-bottom:1.5rem' },
    {s: true,
      name: '.mgb2',
      type: 'margin-bottom:2rem' },
    {s: true,
      name: '.mgb2-5',
      type: 'margin-bottom:2.5rem' },
    {s: true,
      name: '.mgb3',
      type: 'margin-bottom:3rem' },
    {s: true,
      name: '.mgb3-5',
      type: 'margin-bottom:3.5rem' },
    {s: true,
      name: '.mgb4',
      type: 'margin-bottom:4rem' },
    {s: true,
      name: '.mgb4-5',
      type: 'margin-bottom:4.5rem' },
    {s: true,
      name: '.mgb5',
      type: 'margin-bottom:5rem' },
    {s: true,
      name: '.mgb5-5',
      type: 'margin-bottom:5.5rem' },
    {s: true,
      name: '.mgb6',
      type: 'margin-bottom:6rem' },
    {s: true,
      name: '.mgb6-5',
      type: 'margin-bottom:6.5rem' },
    {s: true,
      name: '.mgb7',
      type: 'margin-bottom:7rem' },
    {s: true,
      name: '.mgb7-5',
      type: 'margin-bottom:7.5rem' },
    {s: true,
      name: '.mgb8',
      type: 'margin-bottom:8rem' },
    {s: true,
      name: '.mgb8-5',
      type: 'margin-bottom:8.5rem' },
    {s: true,
      name: '.mgb9',
      type: 'margin-bottom:9rem' },
    {s: true,
      name: '.mgb9-5',
      type: 'margin-bottom:9.5rem' },

    {s: true,
      name: '.mgt-1',
      type: 'margin-top:.1rem' },
    {s: true,
      name: '.mgt-2',
      type: 'margin-top:.2rem' },
    {s: true,
      name: '.mgt-3',
      type: 'margin-top:.3rem' },
    {s: true,
      name: '.mgt-4',
      type: 'margin-top:.4rem' },
    {s: true,
      name: '.mgt-5',
      type: 'margin-top:.5rem' },
    {s: true,
      name: '.mgt-6',
      type: 'margin-top:.6rem' },
    {s: true,
      name: '.mgt-7',
      type: 'margin-top:.7rem' },
    {s: true,
      name: '.mgt-8',
      type: 'margin-top:.8rem' },
    {s: true,
      name: '.mgt-9',
      type: 'margin-top:.9rem' },
    {s: true,
      name: '.mgt1',
      type: 'margin-top:1rem' },
    {s: true,
      name: '.mgt1-5',
      type: 'margin-top:1.5rem' },
    {s: true,
      name: '.mgt2',
      type: 'margin-top:2rem' },
    {s: true,
      name: '.mgt2-5',
      type: 'margin-top:2.5rem' },
    {s: true,
      name: '.mgt3',
      type: 'margin-top:3rem' },
    {s: true,
      name: '.mgt3-5',
      type: 'margin-top:3.5rem' },
    {s: true,
      name: '.mgt4',
      type: 'margin-top:4rem' },
    {s: true,
      name: '.mgt4-5',
      type: 'margin-top:4.5rem' },
    {s: true,
      name: '.mgt5',
      type: 'margin-top:5rem' },
    {s: true,
      name: '.mgt5-5',
      type: 'margin-top:5.5rem' },
    {s: true,
      name: '.mgt6',
      type: 'margin-top:6rem' },
    {s: true,
      name: '.mgt6-5',
      type: 'margin-top:6.5rem' },
    {s: true,
      name: '.mgt7',
      type: 'margin-top:7rem' },
    {s: true,
      name: '.mgt7-5',
      type: 'margin-top:7.5rem' },
    {s: true,
      name: '.mgt8',
      type: 'margin-top:8rem' },
    {s: true,
      name: '.mgt8-5',
      type: 'margin-top:8.5rem' },
    {s: true,
      name: '.mgt9',
      type: 'margin-top:9rem' },
    {s: true,
      name: '.mgt9-5',
      type: 'margin-top:9.5rem' },

    {s: true,
      name: '.mgl-1',
      type: 'margin-left:.1rem' },
    {s: true,
      name: '.mgl-2',
      type: 'margin-left:.2rem' },
    {s: true,
      name: '.mgl-3',
      type: 'margin-left:.3rem' },
    {s: true,
      name: '.mgl-4',
      type: 'margin-left:.4rem' },
    {s: true,
      name: '.mgl-5',
      type: 'margin-left:.5rem' },
    {s: true,
      name: '.mgl-6',
      type: 'margin-left:.6rem' },
    {s: true,
      name: '.mgl-7',
      type: 'margin-left:.7rem' },
    {s: true,
      name: '.mgl-8',
      type: 'margin-left:.8rem' },
    {s: true,
      name: '.mgl-9',
      type: 'margin-left:.9rem' },
    {s: true,
      name: '.mgl1',
      type: 'margin-left:1rem' },
    {s: true,
      name: '.mgl1-5',
      type: 'margin-left:1.5rem' },
    {s: true,
      name: '.mgl2',
      type: 'margin-left:2rem' },
    {s: true,
      name: '.mgl2-5',
      type: 'margin-left:2.5rem' },
    {s: true,
      name: '.mgl3',
      type: 'margin-left:3rem' },
    {s: true,
      name: '.mgl3-5',
      type: 'margin-left:3.5rem' },
    {s: true,
      name: '.mgl4',
      type: 'margin-left:4rem' },
    {s: true,
      name: '.mgl4-5',
      type: 'margin-left:4.5rem' },
    {s: true,
      name: '.mgl5',
      type: 'margin-left:5rem' },
    {s: true,
      name: '.mgl5-5',
      type: 'margin-left:5.5rem' },
    {s: true,
      name: '.mgl6',
      type: 'margin-left:6rem' },
    {s: true,
      name: '.mgl6-5',
      type: 'margin-left:6.5rem' },
    {s: true,
      name: '.mgl7',
      type: 'margin-left:7rem' },
    {s: true,
      name: '.mgl7-5',
      type: 'margin-left:7.5rem' },
    {s: true,
      name: '.mgl8',
      type: 'margin-left:8rem' },
    {s: true,
      name: '.mgl8-5',
      type: 'margin-left:8.5rem' },
    {s: true,
      name: '.mgl9',
      type: 'margin-left:9rem' },
    {s: true,
      name: '.mgl9-5',
      type: 'margin-left:9.5rem' },

    {s: true,
      name: '.mgr-1',
      type: 'margin-right:.1rem' },
    {s: true,
      name: '.mgr-2',
      type: 'margin-right:.2rem' },
    {s: true,
      name: '.mgr-3',
      type: 'margin-right:.3rem' },
    {s: true,
      name: '.mgr-4',
      type: 'margin-right:.4rem' },
    {s: true,
      name: '.mgr-5',
      type: 'margin-right:.5rem' },
    {s: true,
      name: '.mgr-6',
      type: 'margin-right:.6rem' },
    {s: true,
      name: '.mgr-7',
      type: 'margin-right:.7rem' },
    {s: true,
      name: '.mgr-8',
      type: 'margin-right:.8rem' },
    {s: true,
      name: '.mgr-9',
      type: 'margin-right:.9rem' },
    {s: true,
      name: '.mgr1',
      type: 'margin-right:1rem' },
    {s: true,
      name: '.mgr1-5',
      type: 'margin-right:1.5rem' },
    {s: true,
      name: '.mgr2',
      type: 'margin-right:2rem' },
    {s: true,
      name: '.mgr2-5',
      type: 'margin-right:2.5rem' },
    {s: true,
      name: '.mgr3',
      type: 'margin-right:3rem' },
    {s: true,
      name: '.mgr3-5',
      type: 'margin-right:3.5rem' },
    {s: true,
      name: '.mgr4',
      type: 'margin-right:4rem' },
    {s: true,
      name: '.mgr4-5',
      type: 'margin-right:4.5rem' },
    {s: true,
      name: '.mgr5',
      type: 'margin-right:5rem' },
    {s: true,
      name: '.mgr5-5',
      type: 'margin-right:5.5rem' },
    {s: true,
      name: '.mgr6',
      type: 'margin-right:6rem' },
    {s: true,
      name: '.mgr6-5',
      type: 'margin-right:6.5rem' },
    {s: true,
      name: '.mgr7',
      type: 'margin-right:7rem' },
    {s: true,
      name: '.mgr7-5',
      type: 'margin-right:7.5rem' },
    {s: true,
      name: '.mgr8',
      type: 'margin-right:8rem' },
    {s: true,
      name: '.mgr8-5',
      type: 'margin-right:8.5rem' },
    {s: true,
      name: '.mgr9',
      type: 'margin-right:9rem' },
    {s: true,
      name: '.mgr9-5',
      type: 'margin-right:9.5rem' }
  ]},
  {node: 'style_border_radius 圆角',
  s: true,
  countent: [
    {s: true,
      name: '.bdr',
      type: 'border-radius' },
    {s: true,
      name: '.bdr-lt',
      type: 'border-radius-left-top' },
    {s: true,
      name: '.bdr-lb',
      type: 'border-radius-left-bottom' },
    {s: true,
      name: '.bdr-rt',
      type: 'border-radius-right-top' },
    {s: true,
      name: '.bdr-rb',
      type: 'border-radius-right-bottom' }
  ]},
  {node: 'style_overflow 超出隐藏',
  s: true,
  countent: [
    {s: true,
      name: '.oh',
      type: 'overflow:hidden' }
  ]},
  {node: 'style_float 浮动',
  s: true,
  countent: [
    {s: true,
      name: '.fl',
      type: 'float:left' },
    {s: true,
      name: '.fr',
      type: 'float:right' }
  ]},
  {node: 'style_position 定位',
  s: true,
  countent: [
    {s: true,
      name: '.pr',
      type: 'position: relative' },
    {s: true,
      name: '.pa',
      type: 'position: absolute' },
    {s: true,
      name: '.pf',
      type: 'position: fixed' }
  ]},
  {node: 'style_text_align 文本对齐方式',
  s: true,
  countent: [
    {s: true,
      name: '.al-l',
      type: 'text-align: left' },
    {s: true,
      name: '.al-c',
      type: 'text-align: center' },
    {s: true,
      name: '.al-r',
      type: 'text-align: right' }
  ]},
  {node: 'style_font_weight 是否粗体',
  s: true,
  countent: [
    {s: true,
      name: '.fw-n',
      type: 'font-weight: normal' },
    {s: true,
      name: '.fw-b',
      type: 'font-weight: bold' }
  ]},
  {node: 'style_layout_center 居中布局',
  s: true,
  countent: [
    {s: true,
      name: '.center',
      type: 'margin: 0 auto' }
  ]},
  {node: 'style_width 百分比宽度',
  s: true,
  countent: [
    {s: true,
      name: '.w-1',
    type: 'width: 1%'},
    {s: true,
      name: '.w-2',
    type: 'width: 2%'},
    {s: true,
      name: '.w-3',
    type: 'width: 3%'},
    {s: true,
      name: '.w-4',
    type: 'width: 4%'},
    {s: true,
      name: '.w-5',
    type: 'width: 5%'},
    {s: true,
      name: '.w-6',
    type: 'width: 6%'},
    {s: true,
      name: '.w-7',
    type: 'width: 7%'},
    {s: true,
      name: '.w-8',
    type: 'width: 8%'},
    {s: true,
      name: '.w-9',
    type: 'width: 9%'},
    {s: true,
      name: '.w1',
    type: 'width: 10%'},
    {s: true,
      name: '.w1-1',
    type: 'width: 11%'},
    {s: true,
      name: '.w1-2',
    type: 'width: 12%'},
    {s: true,
      name: '.w1-3',
    type: 'width: 13%'},
    {s: true,
      name: '.w1-4',
    type: 'width: 14%'},
    {s: true,
      name: '.w1-5',
    type: 'width:15%' },
    {s: true,
      name: '.w1-6',
    type: 'width:16%' },
    {s: true,
      name: '.w1-7',
    type: 'width:17%' },
    {s: true,
      name: '.w1-8',
    type: 'width:18%' },
    {s: true,
      name: '.w1-9',
    type: 'width:19%' },
    {s: true,
      name: '.w2',
    type: 'width: 20%'},
    {s: true,
      name: '.w2-1',
    type: 'width: 21%'},
    {s: true,
      name: '.w2-2',
    type: 'width: 22%'},
    {s: true,
      name: '.w2-3',
    type: 'width: 23%'},
    {s: true,
      name: '.w2-4',
    type: 'width: 24%'},
    {s: true,
      name: '.w2-5',
    type: 'width: 25%'},
    {s: true,
      name: '.w2-6',
    type: 'width: 26%'},
    {s: true,
      name: '.w2-7',
    type: 'width: 27%'},
    {s: true,
      name: '.w2-8',
    type: 'width: 28%'},
    {s: true,
      name: '.w2-9',
    type: 'width: 29%'},
    {s: true,
      name: '.w3',
    type: 'width: 30%'},
    {s: true,
      name: '.w3-1',
    type: 'width: 31%'},
    {s: true,
      name: '.w3-2',
    type: 'width: 32%'},
    {s: true,
      name: '.w3-3',
    type: 'width: 33%'},
    {s: true,
      name: '.w3-3-3',
    type: 'width: 33.33%'},
    {s: true,
      name: '.w3-4',
    type: 'width: 34%'},
    {s: true,
      name: '.w3-5',
    type: 'width: 35%'},
    {s: true,
      name: '.w3-6',
    type: 'width: 36%'},
    {s: true,
      name: '.w3-7',
    type: 'width: 37%'},
    {s: true,
      name: '.w3-8',
    type: 'width: 38%'},
    {s: true,
      name: '.w3-9',
    type: 'width: 39%'},
    {s: true,
      name: '.w4',
    type: 'width: 40%'},
    {s: true,
      name: '.w4-1',
    type: 'width: 41%'},
    {s: true,
      name: '.w4-2',
    type: 'width: 42%'},
    {s: true,
      name: '.w4-3',
    type: 'width: 43%'},
    {s: true,
      name: '.w4-4',
    type: 'width: 44%'},
    {s: true,
      name: '.w4-5',
    type: 'width:45%' },
    {s: true,
      name: '.w4-6',
    type: 'width:46%' },
    {s: true,
      name: '.w4-5',
    type: 'width:47%' },
    {s: true,
      name: '.w4-8',
    type: 'width:48%' },
    {s: true,
      name: '.w4-9',
    type: 'width:49%' },
    {s: true,
      name: '.w5',
    type: 'width: 50%'},
    {s: true,
      name: '.w5-5',
    type: 'width:55%' },
    {s: true,
      name: '.w6',
    type: 'width: 60%'},
    {s: true,
      name: '.w6-5',
    type: 'width:65%' },
    {s: true,
      name: '.w7',
    type: 'width: 70%'},
    {s: true,
      name: '.w7-5',
    type: 'width:75%' },
    {s: true,
      name: '.w8',
    type: 'width: 80%'},
    {s: true,
      name: '.w8-5',
    type: 'width:85%' },
    {s: true,
      name: '.w9',
    type: 'width: 90%'},
    {s: true,
      name: '.w9-1',
    type: 'width:91%' },
    {s: true,
      name: '.w9-2',
    type: 'width:92%' },
    {s: true,
      name: '.w9-3',
    type: 'width:93%' },
    {s: true,
      name: '.w9-4',
    type: 'width:94%' },
    {s: true,
      name: '.w9-5',
    type: 'width:95%' },
    {s: true,
      name: '.w9-6',
    type: 'width:96%' },
    {s: true,
      name: '.w9-7',
    type: 'width:97%' },
    {s: true,
      name: '.w9-8',
    type: 'width:98%' },
    {s: true,
      name: '.ww',
    type: 'width: 100%'}
  ]},
  {node: 'style_shadow 投影',
  s: true,
  countent: [
    {s: true,
      name: '.shadow',
    type: '阴影'},
    {s: true,
      name: '.shadow-top',
    type: '上阴影'},
    {s: true,
      name: '.shadow-bottom',
    type: '下阴影'}
  ]},
  {node: 'style_clearfix 清除浮动',
  s: true,
  countent: [
    {s: true,
      name: '.clearfix',
    type: '清除'}
  ]},
  {node: 'style_nls li列表样式',
  s: true,
  countent: [
    {s: true,
      name: '.nls',
    type: 'list-style: none'},
    {s: true,
      name: '.ls-o',
    type: 'list-style-position:outside'}
  ]}
];

export default apidata;
